#!/bin/bash

PROGRAM_NAME=$1
PATH_TO_PROGRAM=/home/damian/Desktop
PATH_TO_PATCHED_PROGRAM=/home/damian/projects

if [ -d $PATH_TO_PROGRAM/$PROGRAM_NAME  ] 
then
  if [ -d $PATH_TO_PATCHED_PROGRAM/$PROGRAM_NAME ]
  then
	echo "--------- Appling changes in $PROGRAM_NAME ----------"
	echo "  Changes from directory: $PATH_TO_PROGRAM to directory: $PATH_TO_PATCHED_PROGRAM"

	diff -ru '-x.*' '-xbuild' '-xbitbake' $PATH_TO_PROGRAM/$PROGRAM_NAME $PATH_TO_PATCHED_PROGRAM/$PROGRAM_NAME > $PATH_TO_PATCHED_PROGRAM/file.diff

	sudo rm -R $PATH_TO_PROGRAM/$PROGRAM_NAME

	cd $PATH_TO_PATCHED_PROGRAM
	patch -p0 -R < file.diff

	echo "  ------ FILE/DIRECTORY OCCURENT DIFERENCES ------   "
	cat file.diff | grep "^[ ]*Only in"

	rm file.diff
	cd $PROGRAM_NAME
	find . -type f -name "*.orig" -exec rm {} \;

 
	echo "-------- Finish applying changes ------------"
  else
	echo "[ERROR]: Directory $PATH_TO_PATCHED_PROGRAM/$PROGRAM_NAME does not exist"
 	exit 1
  fi
else
	echo "[ERROR]: Directory $PATH_TO_PROGRAM/$PROGRAM_NAME does not exist"
	exit 1
fi

