#!/bin/bash 


echo -e "\e[00;32m======= COMPILE AND CREATE KERNEL PACKAGE FROM SOURCES=======\e[00m"

KERNEL_VERSION=$1
ADDITIONAL_KERNEL_NAME_SUFFIX=$2
#ARCHITECTURE=$3 #ex amd64

echo -e "\e[00;32mKernel version: $KERNEL_VERSION\e[00m"
echo -e "\e[00;32mAdditional kernel name suffix: $ADDITIONAL_KERNEL_NAME_SUFFIX\e[00m"

echo -e "\e[00;32mInstall dependencies: build-essential ncurses-base ncurses-dev fakeroot kernel-package\e[00m"
sudo apt-get install build-essential ncurses-base ncurses-dev fakeroot kernel-package || exit -1

cd /tmp

echo -e "\e[00;32mDownload kernel sources\e[00m"
wget https://www.kernel.org/pub/linux/kernel/v3.x/linux-$KERNEL_VERSION.tar.xz || exit -1

echo -e "\e[00;32mUnpack kernel sources\e[00m"
tar xvJf linux-$KERNEL_VERSION.tar.xz || exit -1

cd linux-$KERNEL_VERSION

echo -e "\e[00;32mMake menuconfig\e[00m"
make menuconfig || exit -1

export CONCURRENCY_LEVEL=5

echo -e "\e[00;Cleaning before kernel compiling32m\e[00m"
fakeroot make-kpkg clean || exit -1

echo -e "\e[00;32mKERNEL COMPILATION - It may take long time...32m\e[00m"
fakeroot make-kpkg --initrd --append-to-version=-$ADDITIONAL_KERNEL_NAME_SUFFIX kernel_image kernel_headers || exit -1

cp linux-headers-$KERNEL_VERSION-$ADDITIONAL_KERNEL_NAME_SUFFIX* ~/ || exit -1
cp linux-image-$KERNEL_VERSION-$ADDITIONAL_KERNEL_NAME_SUFFIX* ~/ |+ exit -1

echo -e "\e[00;32mKernel compilation done succesfully... 32m\e[00m"
echo -e "\e[00;32mKernel files copied to home directory 32m\e[00m"

