#!/bin/bash

input_file_directory=$2
output_file_directory=$4
action=$1
files_filter="*.$3"
parallel=$5

full_filter=$input_file_directory/$files_filter
echo -e "Full filter: $full_filter" 

for file in $full_filter ; do
  baseName=$(basename $file);
  echo -e "================================"
  echo -e "Processing $baseName..."
  if [ "$output_file_directory" != "" ]; then
	$action "$file" $output_file_path/"$baseName"
  else
        if [ -z $parallel ]; then 
            $action "$file" &
            sleep 0.05s
        else  
            $action "$file" 
        fi
  fi
  echo -e "================================"
done

