#!/usr/bin/python 

import os 
import sys
import glob 
import commands
import itertools 

inputDirectory = sys.argv[1]
sightseewithusLogoPath = "$HOME/sightseeWithUsLogo/sightseewithusLogo.png"
if(len(sys.argv) == 3):
    if(sys.argv[2] == "small"):
        sightseewithusLogoPath = "$HOME/sightseeWithUsLogo/sightseewithusLogoSmall.png"


print "Getting all image files"
imageFilesjpg = glob.glob(inputDirectory + "/*.jpg")
imageFilesJPG = (glob.glob(inputDirectory + "/*.JPG"))
imageFilespng = (glob.glob(inputDirectory + "/*.png"))
imageFilesPNG = (glob.glob(inputDirectory + "/*.PNG"))

imageFiles = itertools.chain(imageFilesjpg, imageFilesJPG, imageFilespng, imageFilesPNG)

#print "Number of files to process: " + str(len(imageFiles))

for imagefile in imageFiles:
    print "Processing file: " + imagefile 
    output = commands.getoutput("identify -verbose " + imagefile)
    lines = output.splitlines();
    orientation  = "Undefined"
    for line in lines:
        if "Orientation:" in line: 
            orientation = line.split(": ")[1]
            break;
    if(orientation == "RightTop"):
        os.system("jpegtran -rotate 90 " + imagefile + " > tmp.jpg");
        os.system("cp tmp.jpg " + imagefile)
        os.system("rm tmp.jpg")

    # embedLogoIntoImage 
    os.system("composite -gravity NorthWest  " + sightseewithusLogoPath + " " + imagefile +  " " + imagefile)


