#!/bin/bash
# Prosty skrypt odpalajacy wybrane przez nas Radio Internetowe

#programowanie podpowiedzi bashowych
complete -W 'RMF_FM Radio_Zet Radio_Lodz Radio_Eska Radiosfera Zlote_Przeboje TOK_FM Radio_Rzeszow Polskie_Niezapomniane_Przeboje Tylko_Polskie_Przeboje Muzyka_Na_TOPIE Przeboje_We_Dwoje Tylko_Rock Radio_Krakowa VOX_FM Radio17 Polskie_Radio_Trojka Polskie_Radio_Dwojka BBC iGol' radio

RADIO=$1
PLAY='yes';
PLAYER=cvlc

if [ $RADIO == 'help' ] 
then
 echo "Dostępne radia: RMF_FM, Radio_Zet, Radio_Lodz, Radio_Eska, Radiosfera, Zlote_Przeboje, TOK_FM, Radio_Rzeszow, Polskie_Niezapomniane_Przeboje, Tylko_Polskie_Przeboje, Muzyka_Na_TOPIE, Przeboje_We_Dwoje, Tylko_Rock, Radio_Krakow, VOX_FM, Radio17, Polskie_Radio_Trojka, Polskie_Radio_Dwojka, BBC, iGol";
 echo "Aby włączyć dane radio wpisz: radio Nazwa_radia_z_listy_wyzej. Np. radio RMF_FM ";
else
  # ${var,,} means lowercased variable 
  case ${RADIO,,} in
    "rmf_fm") adres="http://www.miastomuzyki.pl/n/rmffm.pls" ;;
    "radio_zet") adres="http://radiozetmp3-07.eurozet.pl:8400/;stream" ;;
    "radio_eska") adres="http://olsztyn.radio.pionier.net.pl:8000/z/eska-lodz.ogg" ;;
    "radiosfera") adres="http://serv.radiosfera.pl:7098" ;;
    "zlote_przeboje") adres="http://www.radio.pionier.net.pl/stream.pls?radio=radio88" ;;
    "tok_fm") adres="http://szczecin.radio.pionier.net.pl:8000/pl/radiotok.ogg" ;;
    "radio_rzeszow") adres="http://radio.rzeszow.pl/stereo.pls" ;;
    "polskie_niezapomniane_przeboje") adres="http://www.polskastacja.pl/play/aac_pnp.pls" ;;
    "tylko_polskie_przeboje") adres="http://www.polskastacja.pl/play/aac_tpp.pls" ;;
    "muzyka_na_topie") adres="http://www.polskastacja.pl/play/aac_mnt.pls" ;;
    "przeboje_we_dwoje") adres="http://www.polskastacja.pl/play/aac_love.pls" ;;
    "tylko_rock") adres="http://www.polskastacja.pl/play/aac_rock.pls" ;;
    "radio_krakow") adres="http://www.radio.pionier.net.pl/stream.pls?radio=radiokrakow" ;;   
    "vox_fm") adres="http://www.radio.pionier.net.pl/stream.pls?radio=voxfm" ;;
    "radio17") adres="http://www.radio17.pl/radio17.m3u" ;;
    "polskie_radio_trojka") adres="http://www.polskieradio.pl/st/program3M.asx" ;;
    "polskie_radio_dwojka") adres="http://www.polskieradio.pl/st/program2.asx" ;;
    "polskie_radio_jedynka") adres="http://www.polskieradio.pl/st/program1M.asx" ;;
    "bbc1") adres="http://www.listenlive.eu/bbcradio1.m3u" ;;
    "bbc2") adres="http://www.listenlive.eu/bbcradio2.m3u" ;;
    "bbc3") adres="http://www.listenlive.eu/bbcradio3.m3u" ;;
    "bbc4") adres="http://www.listenlive.eu/bbcradio4.m3u" ;;
    "bbc5live") adres="http://www.listenlive.eu/bbc5live.m3u" ;;
    "bbcleeds") adres="http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/http-icy-mp3-a/vpid/bbc_radio_leeds/format/pls.pls" ;;
    "zakoncz_odtwarzanie") play='no'; killall -9 $PLAYER; killall -9 vlc; notify-send -i gtk-media-stop -t 2500 -u low "RADIO" "Stop playing radio" ;;
    *) PLAY='no'; echo "Błąd! Nie ma takiego radia" ;;
  esac

  if [ $PLAY == 'yes' ]
  then
   notify-send -i gtk-media-play-ltr -u low "RADIO" "Playing radio: $RADIO" 
   killall -9 $PLAYER
   killall -9 vlc
   $PLAYER $adres &
  fi
fi

