#!/bin/bash
# Prosty skrypt odpalajacy wybrane przez nas Radio Internetowe

#programowanie podpowiedzi bashowych
complete -W 'RMF_FM Radio_Zet Radio_Lodz Radio_Eska Radiosfera Zlote_Przeboje TOK_FM Radio_Rzeszow Polskie_Niezapomniane_Przeboje Tylko_Polskie_Przeboje Muzyka_Na_TOPIE Przeboje_We_Dwoje Tylko_Rock Radio_Krakowa VOX_FM Radio17 Polskie_Radio_Trojka Polskie_Radio_Dwojka BBC iGol' radio

RADIO=$1
PLAY='yes';
PLAYER=cvlc

if [ $RADIO == 'help' ] 
then
 echo "Dostępne radia: RMF_FM, Radio_Zet, Radio_Lodz, Radio_Eska, Radiosfera, Zlote_Przeboje, TOK_FM, Radio_Rzeszow, Polskie_Niezapomniane_Przeboje, Tylko_Polskie_Przeboje, Muzyka_Na_TOPIE, Przeboje_We_Dwoje, Tylko_Rock, Radio_Krakow, VOX_FM, Radio17, Polskie_Radio_Trojka, Polskie_Radio_Dwojka, BBC, iGol";
 echo "Aby włączyć dane radio wpisz: radio Nazwa_radia_z_listy_wyzej. Np. radio RMF_FM ";
else
  case $RADIO in
    "RMF_FM") adres="http://www.miastomuzyki.pl/n/rmffm.pls" ;;
    "Radio_Zet") adres="http://radiozetmp3-07.eurozet.pl:8400/;stream" ;;
    "Radio_Eska") adres="http://olsztyn.radio.pionier.net.pl:8000/z/eska-lodz.ogg" ;;
    "Radiosfera") adres="http://serv.radiosfera.pl:7098" ;;
    "Zlote_Przeboje") adres="http://www.radio.pionier.net.pl/stream.pls?radio=radio88" ;;
    "TOK_FM") adres="http://szczecin.radio.pionier.net.pl:8000/pl/radiotok.ogg" ;;
    "Radio_Rzeszow") adres="http://radio.rzeszow.pl/stereo.pls" ;;
    "Polskie_Niezapomniane_Przeboje") adres="http://www.polskastacja.pl/play/aac_pnp.pls" ;;
    "Tylko_Polskie_Przeboje") adres="http://www.polskastacja.pl/play/aac_tpp.pls" ;;
    "Muzyka_Na_TOPIE") adres="http://www.polskastacja.pl/play/aac_mnt.pls" ;;
    "Przeboje_We_Dwoje") adres="http://www.polskastacja.pl/play/aac_love.pls" ;;
    "Tylko_Rock") adres="http://www.polskastacja.pl/play/aac_rock.pls" ;;
    "Radio_Krakow") adres="http://www.radio.pionier.net.pl/stream.pls?radio=radiokrakow" ;;   
    "VOX_FM") adres="http://www.radio.pionier.net.pl/stream.pls?radio=voxfm" ;;
    "Radio17") adres="http://www.radio17.pl/radio17.m3u" ;;
    "Polskie_Radio_Trojka") adres="http://www.polskieradio.pl/st/program3M.asx" ;;
    "Polskie_Radio_Dwojka") adres="http://www.polskieradio.pl/st/program2.asx" ;;
    "Polskie_Radio_Jedynka") adres="http://www.polskieradio.pl/st/program1M.asx" ;;
    "BBC1") adres="http://www.listenlive.eu/bbcradio1.m3u" ;;
    "BBC2") adres="http://www.listenlive.eu/bbcradio2.m3u" ;;
    "BBC3") adres="http://www.listenlive.eu/bbcradio3.m3u" ;;
    "BBC4") adres="http://www.listenlive.eu/bbcradio4.m3u" ;;
    "BBC5live") adres="http://www.listenlive.eu/bbc5live.m3u" ;;
    "BBCLeeds") adres="http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/http-icy-mp3-a/vpid/bbc_radio_leeds/format/pls.pls" ;;
    "Zakoncz_odtwarzanie") PLAY='no'; killall -9 $PLAYER; killall -9 vlc; notify-send -i gtk-media-stop -t 2500 -u low "RADIO" "Stop playing radio" ;;
    *) PLAY='no'; echo "Błąd! Nie ma takiego radia" ;;
  esac

  if [ $PLAY == 'yes' ]
  then
   notify-send -i gtk-media-play-ltr -u low "RADIO" "Playing radio: $RADIO" 
   killall -9 $PLAYER
   killall -9 vlc
   $PLAYER $adres &
  fi
fi

