#! /bin/bash
SERVER_USER=username
SERVER_IP=serverIPAddress
SERVER_PATH=serverPath
MOUNT_POINT=/mnt/mountPoint
OPTIONS="-o allow_other -o direct_io -C"

if [ $(mount | grep $MOUNT_POINT | wc -c ) != 0 ]; then
    echo $MOUNT_POINT "already mounted"
    exit 1
fi

#if [ $(id -u) != 0 ]; then
#    echo "run as root (use sudo)"
#    exit 1
#fi
echo "Input password for remote resource"
sshfs $SERVER_USER@$SERVER_IP:$SERVER_PATH $MOUNT_POINT $OPTIONS

exit $?
