#!/usr/bin/python 

import getpass
import sys
import telnetlib

if(len(sys.argv) != 4):
    print "Error: bad arguments"
    print "Usage: " + sys.argv[0] + " hostIP username commandToRun"
    sys.exit()


HOST = sys.argv[1]
user = sys.argv[2]
command = sys.argv[3] 

tn = telnetlib.Telnet(HOST)

tn.read_until("login: ")
tn.write(user + "\n")
tn.write(command + "\n")
tn.write("exit\n")

print tn.read_all()

