#!/bin/bash
hecho () {
        printf "\e[7m%-`tput cols`s\e[0m\n" "$1"
}
        
hecho "====== OPENCV INSTALL ======"

hecho "Source codes will be downloaded to /tmp directory..."
cd /tmp

hecho "Install dependencies: chkconfig git-core subversion openssh-server"
sudo apt-get install git-core subversion openssh-server \
    build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev \
    python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev \
    libvpx-dev libx264-dev x264 libv4l-dev v4l-utils libopencv-dev build-essential checkinstall cmake pkg-config \
    yasm libjpeg-dev libjasper-dev libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libgstreamer0.10-dev \
    libgstreamer-plugins-base0.10-dev libv4l-dev python-dev python-numpy libtbb-dev libqt4-dev libgtk2.0-dev libfaac-dev \
    libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils \
    cmake qt5-default checkinstall || exit -1

sudo apt-get update

hecho  "Installing newest ffmpeg version "
git clone git://source.ffmpeg.org/ffmpeg.git ffmpeg
cd ffmpeg
./configure --enable-shared --prefix=/usr/local || exit -1
make -j`nproc` || exit -1
sudo make -j`nproc` install || exit -1
sudo ldconfig /usr/local/lib || exit -1
cd ..

hecho "Install OpenCV library "
git clone https://github.com/Itseez/opencv
cd opencv
if [ ! -z $1 ]; then 
    git checkout tags/$1
fi
mkdir -p buildRelease || exit -1
cd buildRelease
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_PYTHON_EXAMPLES=ON \
    -D BUILD_EXAMPLES=ON -D WITH_FFMPEG=ON -D WITH_TBB=ON -D WITH_QT=ON .. || exit -1
exit 1
make -j`nproc` || exit -1
sudo make -j`nproc` install || exit -1
cd ..

hecho "Exporting library to global path"
sudo ldconfig /usr/local/lib || exit -1

hecho "Cleaning after installation"

hecho "OpenCV version installed: "
checkOpenCVVersion

hecho "Installation finished successfully"

