#!/bin/bash 
# Copyright© 2017 Damian Ziobro <damian@xmementoit.com>

PREFIX=/usr/local 

hecho () {
        printf "\e[7m%-`tput cols`s\e[0m\n" "$1"
}

function installGStreamerComponent {
    hecho "============================================================"
    hecho "Installing $1 branch $2"
    hecho "============================================================"

    if [ ! -z $3 ]; then 
      DIR_NAME=$1
      mkdir $DIR_NAME
      cd $DIR_NAME
      wget $3 || exit -1
      tar xjf $(basename $3) 
    else 
      git clone git://github.com/GStreamer/$1 --branch $2 || exit -1
      opts="--disable-gtk-doc --disable-gtk-doc-html --disable-docbook --disable-gtk-doc-pdf"

      if [ $1 == "gst-plugins-bad" ]; then
        opts="$opts --disable-qt --disable-gl"
      fi

      cd $1 || exit -1
      ./autogen.sh --prefix=$PREFIX $opts || exit -1
      make -j`nproc` || exit -1
      sudo make -j`nproc` install || exit -1
      cd ..
    fi
    sudo ldconfig $PREFIX/lib
}


if [ $# -ge 1 ];
then 
    if [ $1 == "-h" ];
    then 
        echo -e "Usage: $(basename $0) version [1]"
        echo -e "           version - version of software which you would like to install ex. 1.4.4"
        echo -e "           1       - optional parameter. If set, then previously installed GStreamer libraries will be removed before installation new version"
        exit -1
    fi

    if [ "$2" == "1" ]; then
      echo -e "Removing preinstalled libraries and includes from /usr/local/include and /usr/local/lib"  
      sudo rm -r /usr/local/include/gstreamer-1.0
      cd /usr/local/lib 
      sudo rm -r gstreamer-1.0 libgst*
      cd -
    fi 

    if [ ! -z $1 ]; then 
      echo -e "Selected GStreamer tag: $1"
      branch=$1
    fi
fi

#install prerequisities
hecho "Installing prerequisities from apt-get..."
sudo apt-get install --yes libtool autotools-dev pkg-config gtk-doc-tools libglib2.0-0 libglib2.0-dev \
    autopoint autoconf libtool libbison-dev flex x264 libx264-dev \
    build-essential freeglut3 freeglut3-dev libgles2-mesa-dev \
    liborc-0.4.0 liborc-0.4-dev ffmpeg libpulse-dev \
    yasm faac librtmp1 librtmp-dev libfaac-dev libfaad-dev || exit -1

branch=${branch:-"master"}

hecho "Installing branch name $branch"

GSTREAMER_DIR=gstreamerInstall
if [ -d $GSTREAMER_DIR ]; then 
    hecho "============================================================"
    hecho "Removing already existing gstreamerInstall dir"
    hecho "============================================================"
    rm -rf $GSTREAMER_DIR
fi
mkdir $GSTREAMER_DIR
cd $GSTREAMER_DIR

echo -e "REMOVING PREVIOUS GSTREAMER FILES"
sudo rm -rf /usr/local/lib/libgst* /usr/local/lib/gstreamer-1.0 &> /dev/null

installGStreamerComponent gstreamer $branch
installGStreamerComponent gst-plugins-base $branch
installGStreamerComponent gst-plugins-good  $branch
installGStreamerComponent gst-plugins-bad  $branch
installGStreamerComponent gst-plugins-ugly  $branch
installGStreamerComponent gst-rtsp-server  $branch
installGStreamerComponent gst-libav  $branch
#installGStreamerComponent gst-android $1 https://gstreamer.freedesktop.org/data/pkg/android/$branch/gstreamer-1.0-android-universal-${branch}.tar.bz2

