#!/bin/bash 

PREFIX=/usr/local 

hecho () {
        printf "\e[7m%-`tput cols`s\e[0m\n" "$1"
}

function installGStreamerComponent {
    hecho "============================================================"
    hecho "Installing $1 branch $2"
    hecho "============================================================"

    git clone git://anongit.freedesktop.org/gstreamer/$1 --branch $2 || exit -1
    cd $1 || exit -1
    ./autogen.sh --prefix=$PREFIX || exit -1
    make -j`nproc` || exit -1
    sudo make -j`nproc` install || exit -1
    cd ..
}


if [ $# -ge 1 ];
then 
    if [ $1 == "-h" ];
    then 
        echo -e "Usage: installGStreamerGitDev [1]"
        echo -e "           1       - optional parameter. If set, then previously installed GStreamer libraries will be removed before installation new version"
        exit -1
    fi

    if [ "$1" == "1" ]; then
      echo -e "Removing preinstalled libraries and includes from /usr/local/include and /usr/local/lib"  
      sudo rm -r /usr/local/include/gstreamer-1.0
      cd /usr/local/lib 
      sudo rm -r gstreamer-1.0 libgst*
      cd -
    elif [ ! -z $1 ]; then 
      echo -e "Selected GStreamer tag: $1"
      branch=$1
    fi
fi

branch=${branch:-"master"}

echo -e "Installing branch name $branch"

GSTREAMER_DIR=gstreamerInstall
mkdir $GSTREAMER_DIR
cd $GSTREAMER_DIR

installGStreamerComponent gstreamer $branch
installGStreamerComponent gst-plugins-base $branch
installGStreamerComponent gst-plugins-good  $branch
installGStreamerComponent gst-plugins-bad  $branch
installGStreamerComponent gst-plugins-ugly  $branch
installGStreamerComponent gst-rtsp-server  $branch
installGStreamerComponent gst-libav  $branch

