#!/bin/bash 

PREFIX=/usr/local 

function installGStreamerComponent {
    echo -e "============================================================"
    echo -e "Installing $1"
    echo -e "============================================================"

    git clone git://anongit.freedesktop.org/gstreamer/$1 || exit -1
    cd $1 || exit -1
    ./autogen.sh --prefix=$PREFIX || exit -1
    make -j`nproc` || exit -1
    sudo make -j`nproc` install || exit -1
    cd ..
}

if [ $1 == "-h" ];
then 
    echo -e "Usage: installGStreamerGitDev [1]"
    echo -e "           1       - optional parameter. If set, then previously installed GStreamer libraries will be removed before installation new version"
    exit -1
fi

if [ $# == 1 ];
then 
    echo -e "Removing preinstalled libraries and includes from /usr/local/include and /usr/local/lib"  
    sudo rm -r /usr/local/include/glib-2.0 /usr/local/include/gstreamer-1.0 /usr/local/include/xercesc /usr/local/include/gio-unix-2.0 
    cd /usr/local/lib 
    sudo rm -r libffi-3.2.1 glib-2.0 gstreamer-1.0 libgrabberConfiguration.so libxerces* libffi* libglib-2.0.* libgmodule-2.0.* libgthread-2.0.* libgobject-2.0.* libgio-2.0.* libgst* pkgconfig*
    cd -
fi

GSTREAMER_DIR=gstreamerInstall
mkdir $GSTREAMER_DIR
cd $GSTREAMER_DIR

installGStreamerComponent gstreamer
installGStreamerComponent gst-plugins-base
installGStreamerComponent gst-plugins-good 
installGStreamerComponent gst-plugins-bad 

