#!/bin/bash

PHRASE_TO_ADD=$1
PHRASE_TO_TRANSLATE=$2

COMPOSED_PHRASE=$PHRASE_TO_ADD" > "$PHRASE_TO_TRANSLATE

echo "$COMPOSED_PHRASE" >> $HOME/.dotfiles/usefulScripts/vocabularyLearner/vocabulary.txt

