#!/bin/bash 

SVN_HOME_DIR="/home/svn"
PROJECT=$1 

#create svn home directory if does not exist 
if [ ! -d $SVN_HOME_DIR ]; then 
  sudo mkdir $SVN_HOME_DIR || exit -1
fi

#create svn repository 
cd $SVN_HOME_DIR
sudo mkdir $PROJECT || exit -1
sudo svnadmin create $SVN_HOME_DIR/$PROJECT || exit -1

cd $SVN_HOME_DIR
sudo chmod -R 777 $PROJECT || exit -1

echo -e "Generating configuration file"

CONF_FILE=$PROJECT/conf/svnserve.conf
#set up write access 
echo -e "[general]" > $CONF_FILE || exit -1
echo -e "anon-access = write" >> $CONF_FILE || exit -1

echo -e "\n\n   SVN repository create successfully \n\n"


