#!/bin/bash

#set -x

if [ -z $1 ]; then 
  echo -e "ERROR: wrong arguments" 
  echo -e "Usage: `basename $0` framerate [lastImageSeconds]"
  echo -e "  Must be invoked from the directory containing images to concatenate"
  exit 100
fi

framerate=$1
lastImageSeconds=$2

if [ -z $2 ]; then
  lastImageSeconds=0
fi

echo -e "framerate: $framerate"
echo -e "lastImageSeconds: $lastImageSeconds"

ls *.PNG &> /dev/null && GLOB_PATTERN=*.PNG;
ls *.JPG &> /dev/null && GLOB_PATTERN=*.JPG;
ls *.png &> /dev/null && GLOB_PATTERN=*.png;
ls *.jpg &> /dev/null && GLOB_PATTERN=*.jpg;
ls *.jpeg &> /dev/null && GLOB_PATTERN=*.jpeg;

echo -e "GLOB_PATTERN: $GLOB_PATTERN"

lastFile=$(ls $GLOB_PATTERN | tail -n 1)
echo "lastFile: $lastFile"

if [ $lastImageSeconds -gt 0 ]; then 
  nrOfCopies=$(($lastImageSeconds*$framerate))
  echo "nrOfCopies: $nrOfCopies"
  for i in $(seq 1 $nrOfCopies); do cp $lastFile ${lastFile}_${i}_.${GLOB_PATTERN##*.}; done
fi

ffmpeg -framerate 3 -pattern_type glob -i "$GLOB_PATTERN" out.mp4

#removing copies of last file
rm *_.${GLOB_PATTERN##*.};

echo -e "Movie successfully outputed into file: out.mp4"
