#! /bin/bash
#
# c.sh
# Copyright (C) 2015 damian <damian@damian-desktop>
#
# Distributed under terms of the MIT license.
#

# Script allow tmux-based copying from selected phrase or line number
# Usage:
#  cf           -> copies from last word of last line 
#  cf 3         -> copies from last word of 3th last line 
#  cf test      -> copies from last word containing 'test'

#WARNING!!!! 
#This script works only with tmux vi-based keys mode 

LINE_NUMBER=3
if [ $# == 1 ];
then
    # check if line_number is really number or regex or substring
    re='^[0-9]+$'
    if ! [[ $1 =~ $re ]] ; 
    then
        LINE_NUMBER=$(($1+1))
        tmux copy-mode \; send-keys ? $1 Enter n Space w h h 
        #echo "error: Not a number" >&2; exit 1
    else 
        LINE_NUMBER=$(($1+2))
        #echo $LINE_NUMBER 
        tmux copy-mode \; send-keys $LINE_NUMBER k h Space b 
    fi
else 
    tmux copy-mode \; send-keys $LINE_NUMBER k h Space b 
fi

COPIED_STRING=`tmux show-buffer`
echo $COPIED_STRING

