#! /bin/bash
#
# c.sh
# Copyright (C) 2015 damian <damian@damian-desktop>
#
# Distributed under terms of the MIT license.
#

# Script allow tmux-based copying line of selected phrase or line number
# Usage:
#  cl           -> copies last line 
#  cl 3         -> copies 3rd last line 
#  cl test      -> copies last line containing 'test'

#WARNING!!!! 
#This script works only with tmux vi-based keys mode 

LINE_NUMBER=3
if [ $# == 1 ];
then 
    # check if line_number is really number or regex or substring
    re='^[0-9]+$'
    if ! [[ $1 =~ $re ]] ; 
    then
        LINE_NUMBER=$(($1+1))
        tmux copy-mode \; send-keys ? $1 Enter n $ h Space ^ Enter  
    else 
        LINE_NUMBER=$(($1+2))
        tmux copy-mode \; send-keys $LINE_NUMBER k $ h Space ^ Enter 
    fi
else
    tmux copy-mode \; send-keys $LINE_NUMBER k $ h Space ^ Enter 
fi

COPIED_STRING=`tmux show-buffer`
echo $COPIED_STRING

