#! /bin/bash
#
# c.sh
# Copyright (C) 2015 damian <damian@damian-desktop>
#
# Distributed under terms of the MIT license.
#

# Script allow tmux-based copying word of selected phrase or line number
# Usage:
#  cw           -> copies last word of last line 
#  cw 3         -> copies last word of 3rd last line 
#  cw test      -> copies last word containing 'test'

#WARNING!!!! 
#This script works only with tmux vi-based keys mode 

LINE_NUMBER=2
if [ $# == 1 ];
then
    # check if line_number is really number or regex or substring
    re='^[0-9]+$'
    if ! [[ $1 =~ $re ]] ; 
    then
        tmux copy-mode \; send-keys ? $1 Enter n b Space w h h Enter  
        #echo "error: Not a number" >&2; exit 1
    else 
        LINE_NUMBER=$(($1+1))
        #echo $LINE_NUMBER 
        tmux copy-mode \; send-keys $LINE_NUMBER k h Space b Enter 
    fi
else 
    tmux copy-mode \; send-keys $LINE_NUMBER k h Space b Enter 
fi

COPIED_STRING=`tmux show-buffer -b 0`
echo $COPIED_STRING

