#!/usr/bin/python
import atom
import getopt
import sys
import string
import time 
import os
import subprocess

#=====================================================================================================
# END OF GOOGLECALENDAR CLASS
#=====================================================================================================

#Global values 
ONE_MINUTE          = 60
TEN_MINUTES         = 10*ONE_MINUTE 
HALF_AN_HOUR        = 30*ONE_MINUTE 
ONE_HOUR            = 60*ONE_MINUTE 
SIX_HOURS           =  6*ONE_HOUR
HOURS_24            = 24*ONE_HOUR
HOURS_48            = 48*ONE_HOUR 
ONE_WEEK            = 7*HOURS_24 
ONE_MONTH           = 30*HOURS_24
SIX_MONTHS          = 6*ONE_MONTH 
ONE_YEAR            = 12*ONE_MONTH

def cmd_exists(cmd):
        return subprocess.call("type " + cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE) == 0

#print variable name 
def namestr(obj, namespace):
        for name in namespace: 
            if namespace[name] is obj: 
                return name 
        return None

def addRepetitionSchedule(title):
    repetitionFrequancies = [TEN_MINUTES, ONE_HOUR, SIX_HOURS, HOURS_24, HOURS_48, ONE_WEEK, ONE_MONTH, SIX_MONTHS, ONE_YEAR]
    #repetitionFrequancies = [TEN_MINUTES, HOURS_24]

    commandBasic = "gcalcli --calendar 'Repetitions' --duration 30 --reminder 10 --where GMT --description '' "

    for i in range(0,len(repetitionFrequancies)):
        full_title = title + " - repetition nr " + str(i) + " - " + namestr(repetitionFrequancies[i], globals()) + " after learning..."
        print "==============================================================================================================================="
        print "Add calendar event => " + full_title
        start_time = time.strftime('%m/%d/%Y %H:%M', time.gmtime(time.time() + repetitionFrequancies[i]))
        command = commandBasic + "--title '" + title + "' --when '" + start_time + "' add"
        #print command
        os.system(command)


 
def main():
  if len(sys.argv) != 2:
      print (sys.argv[0]+' --title=[title] ')
      sys.exit(2)

  if not cmd_exists("gcalcli"):
      print("ERROR: command 'gcalcli' is not installed on this computer. Please install it according to this instruction: https://github.com/insanum/gcalcli")
      sys.exit(3)

  title = sys.argv[1]

  #calendarUrl = "/calendar/feeds/hr9kl844emegiicji5h9fku8h0%40group.calendar.google.com/private/full"
  addRepetitionSchedule(title)
  print ("===========================================================================")
  print ("Adding title: '" + title + "' to RepetitionList.txt Google Drive file")
  #os.system("appendLineToGDriveFile RepetitionList.txt \"" + title +"\"");
  os.system("echo " + title + " >> " + os.getenv("DATA_DIR") + "/Documents/RepetitionList.txt");
  print ("===========================================================================")

if __name__ == '__main__':
  main()
